name: CAPS
channels:
  - defaults
  - pip:
    - absl-py==1.1.0
    - alembic==1.8.0
    - attrs==21.4.0
    - autopage==0.5.1
    - cachetools==5.2.0
    - charset-normalizer==2.0.12
    - cliff==3.10.1
    - cloudpickle==2.1.0
    - cmaes==0.8.2
    - cmd2==2.4.1
    - colorlog==6.6.0
    - convertdate==2.4.0
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.47.0
    - gym==0.24.1
    - gym-notices==0.0.7
    - hijri-converter==2.2.4
    - holidays==0.13
    - idna==3.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.8.0
    - kaleido==0.2.1
    - korean-lunar-calendar==0.2.1
    - mako==1.2.0
    - markdown==3.3.7
    - markupsafe==2.1.1
    - oauthlib==3.2.0
    - optuna==2.10.1
    - pbr==5.9.0
    - prettytable==3.3.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymeeus==0.5.11
    - pyperclip==1.8.2
    - pyyaml==6.0
    - requests==2.28.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.1
    - sqlalchemy==1.4.39
    - stevedore==3.5.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tqdm==4.64.0
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - werkzeug==2.1.2
    - zipp==3.8.0
